### ISSUE TITLE
Security model and SSL connection

### ISSUE THREAD

**Issue by millerdev** [lynxaegon/obsidian-anysocket-sync#6]
Thanks for writing this plugin. I'm curious about the security model.

In particular, is the password sent over the network in the clear if SSL (HTTPS) is not used? Is it safe to expose port 3000 on the public Internet when not using SSL?

Secondly, I have an NGINX proxy that does SSL termination for my [server](https://github.com/lynxaegon/obsidian-anysocket-sync-server), but cannot seem to get obsidian-anysocket-sync to connect when I point it at NGINX + port 443. Is that expected to work? How/can I tell anysocket to use SSL?

**Comment by lynxaegon** [comment]
Glad you like the plugin :) 

Regarding the security model, the password is not really sent in clear text, it has some prefix & suffix derived from the unique anysocket id, but without using https, the password can be captured with MITM attacks and yes, the same "password" can be sent to the server and connect, but only one connection with the same anysocket id is allowed. 

After you connect to the server, the servers upgrades the connection to end-to-end encrypted with forward secrecy, using ECDH P-521. This is quite safe, but the initial connection (over http) is still prone to MITM attacks.

Regarding the nginx with SSL termination, i really didn't try nginx in front of anysocket, but i don't see why it shouldn't work, because it's a normal WebSocket connection. If you want to enable SSL you can just put the pk and cert somewhere and then in the config, uncomment these lines and update with the correct paths.
```
    // optional, enables https
    // "certs": {
    //     "pk": "./certs/privkey.pem",
    //     "cert": "./certs/fullchain.pem"
    // },
````

If you want to read more about anysocket, you can look here: https://github.com/lynxaegon/anysocket

**Comment by millerdev** [comment]
> If you want to enable SSL you can just put the pk and cert somewhere...

Would it be possible to add a plugin setting to tell it to use SSL when connecting to the server? The server does not have access to the filesystem where the SSL cert resides because it's running in a container. Besides, I'd prefer not to expose the cert to the anysocket server since it doesn't need it.

**Comment by lynxaegon** [comment]
By default, when it connects to the server it first tries SSL then without SSL. I'll look into why it's not connecting over proxying via nginx, it should have worked

**Comment by lynxaegon** [comment]
I have tested with a basic proxy configuration in nginx:

```
server {
        listen 8080 default_server;
        listen [::]:8080default_server;

        # SSL configuration
        #
        listen 8443 ssl default_server;
        listen [::]:8443 ssl default_server;

        ssl_certificate     /root/dev/certs/fullchain.pem;
        ssl_certificate_key /root/dev/certs/privkey.pem;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
            proxy_pass http://127.0.0.1:3000;
            proxy_set_header Host $host;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

}
```

This works flawlessly. I had no issues and it's connected over SSL

**Comment by millerdev** [comment]
Thanks for looking into that. It appears to be working for me now too. Previously I did not have these lines in my config
```
            proxy_set_header Host $host;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
```
so maybe adding them fixed the issue?
